# Generated by Django 3.2.7 on 2023-04-22 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('transactionType', models.CharField(default='deposit', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parkCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='residents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentbalance',
            name='student',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='totalprice',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='student',
            new_name='parkCustomer',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transactionid',
            new_name='transactionId',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transactiontime',
            new_name='transactionTime',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='fooditem',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='quantity',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transactionType',
            field=models.CharField(default='withdraw', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BreakfastTrans',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Residents',
        ),
        migrations.AlterField(
            model_name='paynowpayment',
            name='balance',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.customerbalance'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.customerbalance'),
        ),
        migrations.DeleteModel(
            name='Studentbalance',
        ),
    ]
